name    'AlexCline-dirtree'
version '0.1.0'
author 'Alex Cline <alex.cline@gmail.com>'
license 'Apache License, Version 2.0'
summary 'A module to provide a dirtree function which returns an array of a directory tree from a path string.'
description 'A module to provide a dirtree function which returns an array of a directory tree from a path string.'
project_page 'https://github.com/AlexCline/dirtree'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
